services:
  db:
    image: postgres:16
    container_name: tcgmarket-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tcgmarket

  userservice:
    build:
      context: ../services/trust_layer/userservice
    container_name: tcgmarket-userservice
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ../services/trust_layer/userservice/app:/app/app
  
  cardref:
    build:
      context: ../services/api/cardref
    container_name: tcgmarket-cardref
    restart: unless-stopped
    ports:
      - "8001:8000"
    depends_on:
      - db
    env_file:
      - ../infra/.env
    volumes:
      - ../services/api/cardref:/app
      - ../infra/.env:/app/.env
      - ../services/api/cardref/data:/app/data


  frontend-web:
    image: node:20
    container_name: tcgmarket-frontend-web
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ../services/frontend/web:/app
    command: sh -c "npm install && npm run dev -- --host"

volumes:
  pgdata:
